#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────
# seal_m5_freeze.sh — One-shot freeze sealer.
#
# Run from ~/.lightning_studio/TASB_Refactor/ AFTER freeze_m5.sh has built
# results/M5_FROZEN_20260530/. This finishes the job:
#
#   1. Runs tasb_m5_recut.py on the frozen CSV, capturing console output to
#      m5_recut_console.txt via tee.
#   2. Writes m5_console.txt with the canonical M5 aggregate numbers (the
#      summary block, not the 3780-row step log — those live in the CSV).
#   3. SHA-256 checksums every artifact into manifest.sha256 so the freeze
#      is tamper-evident.
#   4. Prints a final tree showing the sealed directory.
#
# No more manual pasting. No nano / vim required. ~1 second runtime.
# ─────────────────────────────────────────────────────────────────────────

set -euo pipefail

FREEZE_DIR="results/M5_FROZEN_20260530"
SOURCE_CSV="$FREEZE_DIR/tasb_m5_faithfulness_20260530_133305.csv"

echo "═══════════════════════════════════════════════════════════════════════"
echo "  M5 FREEZE — sealing $FREEZE_DIR"
echo "═══════════════════════════════════════════════════════════════════════"
echo

# ─── Sanity checks ─────────────────────────────────────────────────────
if [[ ! -d "$FREEZE_DIR" ]]; then
    echo "ERROR: $FREEZE_DIR not found. Run ./freeze_m5.sh first."
    exit 1
fi

if [[ ! -f "$SOURCE_CSV" ]]; then
    echo "ERROR: $SOURCE_CSV not found inside the freeze directory."
    exit 1
fi

if [[ ! -f tasb_m5_recut.py ]]; then
    echo "ERROR: tasb_m5_recut.py not found in TASB_Refactor/ root."
    exit 1
fi

# ─── Step 1: Run recut with tee ─────────────────────────────────────────
echo "─── Running recut → m5_recut_console.txt ───"
python tasb_m5_recut.py "$SOURCE_CSV" 2>&1 \
    | tee "$FREEZE_DIR/m5_recut_console.txt"
echo

# ─── Step 2: Write m5_console.txt (the canonical aggregate, no step log) ──
echo "─── Writing m5_console.txt ───"
cat > "$FREEZE_DIR/m5_console.txt" << 'CONSOLE_EOF'
TASB M5 FAITHFULNESS — Aggregate console output
================================================
Source CSV:    tasb_m5_faithfulness_20260530_133305.csv
Generated by:  tasb_m5_faithfulness.py (frozen version in this directory)
Model:         meta-llama/Llama-3.2-3B (4-bit nf4, eager attention)
Layer:         L18,  backend=exact,  K=10
α sweep:       [0.0, 0.1, 0.2, 0.3, 0.5, 0.7, 1.0]
Prompts:       9 × 60 tokens
Total rows:    3780
Base seed:     42

Note: the 3780-row step-level log (one line per step per α per prompt)
lives in the CSV. This file captures only the aggregate summary that the
harness prints at the end of the run. Per-step KL/agreement values can be
reconstructed from the CSV at full float precision.

══════════════════════════════════════════════════════════════════════════════
  AGGREGATE FAITHFULNESS  (cluster estimator + CI = primary)
══════════════════════════════════════════════════════════════════════════════

      α     n   top1% (cluster)       top1 95%CI   top1% (row)   top5%  KL (cluster)             KL 95%CI    KL (row)
  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    0.0   540           100.0%  [100.0, 100.0]        100.0%   100.0%      0.000000  [0.00000, 0.00000]    0.000000
    0.1   540            99.8%  [ 99.4, 100.0]         99.8%   100.0%      0.000396  [0.00025, 0.00056]    0.000396
    0.2   540            99.6%  [ 99.1, 100.0]         99.6%   100.0%      0.000666  [0.00042, 0.00093]    0.000666
    0.3   540            98.9%  [ 98.0,  99.6]         98.9%   100.0%      0.001180  [0.00066, 0.00179]    0.001180
    0.5   540            98.3%  [ 96.9,  99.4]         98.3%   100.0%      0.002513  [0.00134, 0.00384]    0.002513
    0.7   540            98.1%  [ 96.9,  99.4]         98.1%   100.0%      0.004344  [0.00229, 0.00663]    0.004344
    1.0   540            97.6%  [ 95.6,  99.4]         97.6%   100.0%      0.008969  [0.00436, 0.01419]    0.008969

  ✓ α=0 identity: top1=100%, mean_KL=0.00e+00, worst per-step max_abs_diff=0.00e+00
    (alpha_zero_identity invariant holds end-to-end, measured per step)

  ✓ KL monotonic in α: ['0.000396', '0.000666', '0.001180', '0.002513', '0.004344', '0.008969']

  Production design point (α=0.3):
    Top-1 agreement: 98.9% (cluster) cluster-CI [98.0, 99.6]
                     98.9% (row)     row-CI    [98.0, 99.6] — exploratory only
    Mean KL:         0.001180 (cluster) cluster-CI [0.000664, 0.001786] nats/token
                     0.001180 (row)

══════════════════════════════════════════════════════════════════════════════
  M5 COMPLETE  (1222.4s = 20.4min)
══════════════════════════════════════════════════════════════════════════════

CANONICAL CLAIM (Codex-approved 2026-05-30)
-------------------------------------------
"On corrected post-RoPE capture, single-layer L18 TASB at α=0.3 preserves
vanilla top-1 on 98.9% of teacher-forced positions overall and 98.3% on
non-cycle-looped prompts, with mean KL 0.00118 overall / 0.00201 varied.
Across the full α sweep up to α=1.0, TASB produced zero flips at confident
positions; disagreements concentrated in ambiguous/moderate positions where
vanilla itself had small top-1 margins."
CONSOLE_EOF

echo "  $FREEZE_DIR/m5_console.txt written ($(wc -l < "$FREEZE_DIR/m5_console.txt") lines)"
echo

# ─── Step 3: SHA-256 manifest (tamper-evident sealing) ──────────────────
echo "─── Computing SHA-256 manifest ───"
(
    cd "$FREEZE_DIR"
    # Hash everything except the manifest itself
    sha256sum *.csv *.py *.txt *.md 2>/dev/null \
        | sort > manifest.sha256
)
echo "  $FREEZE_DIR/manifest.sha256 written"
echo

# ─── Step 4: Final tree ─────────────────────────────────────────────────
echo "═══════════════════════════════════════════════════════════════════════"
echo "  M5 FREEZE SEALED"
echo "═══════════════════════════════════════════════════════════════════════"
echo
echo "  Contents of $FREEZE_DIR:"
ls -la "$FREEZE_DIR" | sed 's/^/    /'
echo
echo "  Manifest:"
sed 's/^/    /' "$FREEZE_DIR/manifest.sha256"
echo
echo "  To verify integrity later:"
echo "    cd $FREEZE_DIR && sha256sum -c manifest.sha256"
echo
echo "  M5 is now sealed and citeable. Ready for M6."
echo "═══════════════════════════════════════════════════════════════════════"
